Repository zuhlke-training/react-frontend, pull requests merged in 2019-03, with the labels that each got.

#2 Implement CircleCI Integration
  .circleci/config.yml
Labels: enhancement

#7 Javo frontend
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/FormWrapper.jsx
  src/apiwrapper.js
  src/components/Card.jsx
  src/components/Form.jsx
  src/components/NewEmployee.jsx
  src/components/NewForm.jsx
  src/setupProxy.js
Labels: enhancement

#8 Configure Cypress Integration Tests
  .circleci/config.yml
  .circleci/run-build-locally-sh
  cypress.json
  cypress/.eslintrc.json
  cypress/fixtures/example.json
  cypress/integration/sample_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: enhancement

#9 Javo frontend
  src/API/APICalls.jsx
  src/API/apiwrapper.js
  src/App.jsx
  src/components/Form.jsx
Labels: enhancement, good first issue

#11 Delete card
  .circleci/run-build-locally-sh
  src/API/APICalls.jsx
  src/API/apiwrapper.js
  src/App.jsx
  src/apiwrapper.js
  src/components/Card.jsx
  src/components/Form.jsx
  src/components/Styled.js
  src/setupProxy.js
Labels: enhancement

#13 Delete confirmation
  src/App.jsx
  src/components/Card.jsx
  src/components/Styled.js
Labels: enhancement

#14 Add employee
  src/API/APICalls.jsx
  src/App.jsx
  src/components/EmployeeForm.jsx
  src/components/Form.jsx
  src/components/Styled.js
  src/setupProxy.js
Labels: enhancement

#15 Edit card
  src/API/APICalls.jsx
  src/App.jsx
  src/components/Card.jsx
Labels: enhancement

#18 Add employee popup
  src/App.jsx
  src/FormWrapper.jsx
  src/components/NewEmployee.jsx
  src/components/NewForm.jsx
  src/components/Styled.js
  src/components/SuccessMessage.jsx
Labels: enhancement

#22 Add CRUD integration tests
  cypress/fixtures/employee.json
  cypress/fixtures/example.json
  cypress/integration/add_employee.js
  cypress/integration/delete_employee.js
  cypress/integration/edit_employee.js
  cypress/integration/render_test.js
  src/components/Card.jsx
  src/components/EmployeeForm.jsx
Labels: enhancement

#25 Sort cards
  cypress/fixtures/employee_page.json
  cypress/integration/sort_employees.js
  src/API/APICalls.jsx
  src/App.jsx
  src/components/Sort.jsx
Labels: enhancement

#24 implement success message for edit and delete
  cypress/integration/add_employee.js
  cypress/integration/delete_employee.js
  cypress/integration/edit_employee.js
  cypress/integration/render_test.js
  src/App.jsx
  src/components/Card.jsx
  src/components/EmployeeForm.jsx
  src/components/SuccessMessage.jsx
Labels: bug, enhancement

#23 Refactor form
  cypress/integration/add_employee.js
  cypress/integration/delete_employee.js
  cypress/integration/edit_employee.js
  src/App.jsx
  src/components/Card.jsx
  src/components/EmployeeForm.jsx
  src/components/Sort.jsx
Labels: refactor
